name: iact3-test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0
        
    - name: Use secret
        run: |
          echo ${{ secrets.ACCESS_KEY_ID }}

    - name: Find changed templates
      id: changed-templates
      run: |
        echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        echo $(git diff --name-only -r HEAD^1 HEAD | xargs)
        

    - name: Test templates
      uses: Achillessanger/iact3-action@v2
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: test-templates

    - name: DingTalk Robot
      if: always()
      run: |
        if [[ "${{ steps.test-templates.outputs.status }}" = "success" ]]; then
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-test CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        else
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-test CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        fi




