name: iact3-validate

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        if ${{ github.repository == 'Achillessanger/iact3-document' }}; then
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout -qf FETCH_HEAD
          echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)" >> $GITHUB_OUTPUT
          echo $(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)
        else
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          echo $(git diff --name-only -r HEAD^1 HEAD | xargs)
        fi
        

    - name: Test templates
      uses: Achillessanger/iact3-action@v2
      if: github.repository == 'Achillessanger/iact3-document'
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: test-templates

    - name: Validate templates
      uses: Achillessanger/iact3-action@main
      if: github.repository != 'Achillessanger/iact3-document'
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: validate-templates

    - name: DingTalk Robot
      if: always()
      run: |
        if ${{ github.repository == 'Achillessanger/iact3-document' }}; then
          if [[ "${{ steps.test-templates.outputs.status }}" = "success" ]]; then
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          else
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          fi
        else
          if [[ "${{ steps.validate-templates.outputs.status }}" = "success" ]]; then
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          else
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          fi
        fi
        
  



