name: iact3-validate

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        git checkout -qf FETCH_HEAD
        echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)" >> $GITHUB_OUTPUT
        echo $(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)

    - name: Test templates
      uses: Achillessanger/iact3-action@v2
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: test-templates

 
        
  



