name: iact3-validate

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Validate:
    runs-on: ubuntu-latest

    steps:
    - name:  White list
      id: white-list
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        echo "::::"
        echo $(curl -sSL -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
        echo ${{ github.actor }}
        kk=$(curl -sSL -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
        echo $kk
        
        if grep -q ${{ github.actor }} $kk ; then
          echo "is white"
        else
          echo "not in white"
        fi
        
        is_white=$(curl -sSL -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login' | grep -c "${{ github.actor }}")

          
        echo "role=$is_white" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        echo "::"${{ github.event.pull_request.author_association }}
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
        git checkout -qf FETCH_HEAD
        echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)" >> $GITHUB_OUTPUT
        echo $(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)

    - name: Test templates
      uses: Achillessanger/iact3-action@v2
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: test-templates
      if: ${{ steps.white-list.outputs.role == '1' }}

    - name: Validate templates
      uses: Achillessanger/iact3-action@main
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: validate-templates
      if: ${{ steps.white-list.outputs.role != '1' }}

    - name: DingTalk Robot
      if: always()
      run: |
        if [[ "${{ steps.white-list.outputs.role  }}" != "1" ]]; then
          if [[ "${{ steps.validate-templates.outputs.status }}" = "success" ]]; then
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          else
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-validate CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          fi
        else
          if [[ "${{ steps.test-templates.outputs.status }}" = "success" ]]; then
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-test CI pass. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          else
            curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "Iact3-test CI failed. ${{ github.event.pull_request.user.login }} PR#${{ github.event.pull_request.number }}:${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
          fi
        fi
        
  



