name: iact3-test

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  iact3Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        if ${{ github.event_name == 'pull_request_target' }}; then
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout -qf FETCH_HEAD
          echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main)  | xargs)" >> $GITHUB_OUTPUT
        else
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}  | xargs)" >> $GITHUB_OUTPUT
        fi

    - name: Test templates
      uses: Achillessanger/iact3-action@main
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
      id: test-templates

    - name: DingTalk Robot
      if: always()
      run: |
        if [[ "${{ steps.test-templates.outputs.status }}" = "success" ]]; then
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "PR#${{ github.event.pull_request.number }} iact3-test pass: ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        else
          curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "PR#${{ github.event.pull_request.number }} iact3-test failed: ${{ github.event.pull_request.html_url }} "}}' ${{ secrets.DINGDING_WEBHOOK }}
        fi
  



