name: iact3-test-push

on:
  push:
    branches:
      - main

jobs:
  iact3Test:
    runs-on: ubuntu-latest

    steps:
    - name:  contributors
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        
        collaborators=$(curl -sSL -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login | xargs')
        echo "Repository collaborators: $collaborators"
        echo "::"${{ contains($collaborators, github.actor) }}
        if [ $r -eq 1 ]; then
          echo "User is a contributor"
            # 使用某一个 action
        else
          echo "User is not a contributor"
            # 使用另一个 action
        fi

    - uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Find changed templates
      id: changed-templates
      run: |
        echo "::"${{ contains(github.repository.collaborators, github.actor) }}
   
        
        if ${{ github.event_name == 'pull_request_target' }}; then
          echo "github.event_name == pull_request_target"
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout -qf FETCH_HEAD
          echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main) | xargs)" >> $GITHUB_OUTPUT
        else
          echo "github.event_name != pull_request_target"
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}  | xargs)" >> $GITHUB_OUTPUT
        fi
        echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}  | xargs)

    - name: Test templates
      uses: Achillessanger/iact3-action@v2
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
#      continue-on-error: true
      id: test-templates
      if: ${{ contains(github.repository.collaborators, github.actor) }}


    - name: DingTalk Robot
      if: always()
      run: |
        curl -H 'Content-Type: application/json;charset=utf-8' -d '{"msgtype": "text","text": {"content": "测试结果：https://github.com/${{ github.repository }}/commit/${{ github.sha }}"}}' ${{ secrets.DINGDING_WEBHOOK }}
  



