name: iact3-test

on:
#  push:
#    branches:
#      - main
  pull_request_target:
    types: [ opened, synchronize, reopened ]


jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2


    - name: Find changed templates
      id: changed-templates
      run: |
        if ${{ github.event_name == 'pull_request_target' }}; then
          echo "github.event_name == pull_request_target"
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
        else
          echo "github.event_name != pull_request_target"
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
        fi
        
        echo "----"
        echo $(git diff --name-only -r HEAD^1 HEAD)
        echo "++++"
#        echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
#        echo "????
        git fetch origin ${{github.base_ref}}:$GITHUB_BASE_REF
        git fetch origin ${{github.head_ref}}:$GITHUB_HEAD_REF
        files=$(git diff --name-only $GITHUB_BASE_REF $GITHUB_HEAD_REF)
        echo "Changed files:"
        echo "$files" | grep --color=never -E ".*"

    - name: Test templates
      uses: Achillessanger/iact3-action@main
      with:
        templates: ${{ steps.changed-templates.outputs.changed_files }}
        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
#      continue-on-error: true
      id: test-templates


    - name: Reject PR
      uses: peter-evans/create-issue-from-file@v4
      if: steps.test-templates.outputs.status == 'fail'
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        title: 'Pull Request Iact3 Check Failed'
        body: |
          Pull request check failed for PR: ${{ github.event.number }}
          
          Click the following link to view the PR:
          https://github.com/${{ github.repository }}/pull/${{ github.event.number }}



